# Generated by Django 2.1.7 on 2019-03-12 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20190227_1918'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_moderator',
            field=models.BooleanField(default=False),
        ),
    ]
